version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: "smena"
      POSTGRES_PASSWORD: "1234512345"
    expose:
      - "5432"
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.12
    expose:
      - "6379"
    ports:
      - 6379:6379
    depends_on:
      - db
  pdfconv:
    image: "openlabs/docker-wkhtmltopdf-aas"
    expose:
      - "80"
    ports:
      - 80:80
    depends_on:
      - redis

